DROP TABLE IF EXISTS POST;

CREATE TABLE POST (
        "POST_ID" VARCHAR2 (100 CHAR) NOT NULL,
        "TITLE" VARCHAR2 (100 CHAR) NOT NULL,
        "IMAGE" VARCHAR2 (100 CHAR) NOT NULL,
        "CONTENT" VARCHAR2 (1000 CHAR) NOT NULL,
        "CATEGORY" VARCHAR2 (50 CHAR) NOT NULL,
        "CREATE_AT" TIMESTAMP,
        "UPDATE_AT" TIMESTAMP,
        PRIMARY KEY ("POST_ID")
);

DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
        "CONTACT_ID" VARCHAR2 (100 CHAR) NOT NULL,
        "NAME" VARCHAR2 (100 CHAR) NOT NULL,
        "EMAIL" VARCHAR2 (100 CHAR) NOT NULL,
        "MESSAGE" VARCHAR2 (1000 CHAR) NOT NULL,
        "CREATE_AT" TIMESTAMP,
        PRIMARY KEY ("CONTACT_ID")
);

DROP TABLE IF EXISTS API_KEY;

CREATE TABLE API_KEY (
        "ID" BIGINT NOT NULL IDENTITY,
        "KEY" VARCHAR2 (50 CHAR) NOT NULL,
        PRIMARY KEY("ID")
)